### ISSUE TITLE
[SSA Edit Page] Edits required window popping up incessantly 

### ISSUE THREAD

**Issue by JessieLOliver** [SciStarter-Team/SciStarter-Bugs#25] opened 2024-11-21 06:58 UTC
Today I jumped to edit a project (just cleaning up the excessive use of hyphens etc). The red colouring implies I have made an error before I even tried to change anything, and the window kept popping up incessantly, preventing me from actually making changes I wanted to in an efficient way. 

<img width="727" alt="image" src="https://github.com/user-attachments/assets/0dd52637-a54e-4449-8673-5b533c19d592">

Additionally, I note that some of the form was somehow submitted without the required fields being filled out, and I am not able to save edits. I put them all in the same issue with the suspicion they are all related. 

<img width="766" alt="image" src="https://github.com/user-attachments/assets/baf352f5-041d-45b8-ba4b-fecaff25134e">

**Comment by JessieLOliver** [comment] 2024-11-21 07:56
The pop up is definitely a bug

**Comment by SciStarter** [comment] 2024-11-21 07:57
Yes, all related. Imported projects do not necessarily follow the conventions that our local form validation enforces, and so the first person who tries to edit the project post-import is required to bring it fully into compliance before being able to save it. This time, that was you.

**Comment by SciStarter** [comment] 2024-11-21 07:57
And no, the pop up is not a bug. It's an unfortunate necessity, because until we added it, people regularly failed to notice that they needed to make changes in the form before saving would succeed, and pinging us with bug reports that the save didn't work.

**Comment by JessieLOliver** [comment] 2024-11-21 08:30
- Note the Drover project (https://scistarter.org/dover-waterwatch) was added on 06/18/2024, 10:06 pm GMT+10, though I don't know when it showed up in the exchange moderation list
- Can you tell if this project was added directly A) to the SSA exchange or B) imported through CitSci.org?
- If A) Then perhaps it was before people were prohibited from not filling out "required" fields, meaning that they could submit without filling out those fields. Perhaps this is why a bunch of required fields are blank in the submission?
- If B) then why did it end up in the exchange for moderation? I thought if it was added to SciStarter.org it wouldn't show in our exchange.  Are CitSci.org project fields not harmonised with required SciStarter fields? What am I missing?
- Either way 1) there is so much missing info, I am not sure I should fill it out, and 2) the edit warning pops up so much though I can't even finish editing within a single field, so I have given up for now.

**Comment by SciStarter** [comment] 2024-11-21 08:39
It originated from CitSci.org and was marked as being owned by your exchange by a manual error on my part. I've fixed that now, so you should not even need to squelch it.

**Closed as completed by SciStarter** 2024-11-21 08:39 UTC
Labels: question
