### ISSUE TITLE
Adding a notes field for squelching

### ISSUE THREAD

**Issue by JessieLOliver** [SciStarter-Team/SciStarter-Bugs#38] opened 2024-12-04 01:28 UTC
Please add the capability to add a note when squelching a project that is also visible to SSA staff once the project is squelched, so long as the staff is signed in. 

Consider adding a tick box if the SSA would like to alert a member of the SSG team of an issue reported in a note.

**Comment by SciStarter** [comment] 2024-12-04 07:55
Duplicate of #33

**Closed as completed by SciStarter** 2024-12-04 07:55 UTC
